name: assist_decisions_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  carousel_slider: ^4.0.0
  file_picker: ^5.2.7

  # flutter/material.dart:
  # flutter/services.dart:
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.17.0 
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: ExtraLight
      fonts:
        - asset: assets/fonts/Kanit-ExtraLight.ttf
    - family: Light
      fonts:
        - asset: assets/fonts/Kanit-Light.ttf
    - family: Medium
      fonts:
        - asset: assets/fonts/Kanit-Medium.ttf
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Regular.ttf
    - family: SemiBold
      fonts:
        - asset: assets/fonts/Kanit-SemiBold.ttf
  uses-material-design: true
  assets:
      - assets/images/
